# Latihan-4 (Operasi matriks)

In [2]:
import numpy as np

In [3]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

## Hitunglah:

1. 2*A
2. 2+A
3. A+B
4. A-B
5. determinan A
6. invers dari B, simpan jadi matriks D
7. transpose D
8. nilai eigen dan vektor eigen dari A dan B

### 1. 2*A

In [4]:
print(2*A)

[[ 2  4]
 [14 16]]


### 2. 2+A

In [5]:
print(2+A)

[[ 3  4]
 [ 9 10]]


### 3. A+B

In [6]:
print(A+B)

[[ 4  7]
 [ 8 14]]


### 4. A-B

In [7]:
print(A-B)

[[-2 -3]
 [ 6  2]]


### 5. Determinan A

In [8]:
print("Determinan Matriks A = ", np.linalg.det(A))

Determinan Matriks A =  -6.0


### 6. Invers dari B, simpan jadi Matriks D

In [12]:
D = np.linalg.inv(B)

In [13]:
D

array([[ 0.46153846, -0.38461538],
       [-0.07692308,  0.23076923]])

### 7. Transpose D

In [15]:
transpose_matriks = np.transpose(D)

In [17]:
transpose_matriks

array([[ 0.46153846, -0.07692308],
       [-0.38461538,  0.23076923]])

### 8. Nilai Eigen dan Vektor Eigen dari A dan B

In [18]:
eig_val, eig_vecs = np.linalg.eig(A)

In [20]:
eig_val

array([-0.62347538,  9.62347538])

In [21]:
eig_vecs

array([[-0.77640358, -0.22592838],
       [ 0.63023605, -0.97414391]])

In [22]:
eig_val, eig_vecs = np.linalg.eig(B)

In [23]:
eig_val

array([1.8074176, 7.1925824])

In [24]:
eig_vecs

array([[-0.97271381, -0.76626443],
       [ 0.23200828, -0.64252535]])